### ISSUE TITLE
通过代码中动态设置的不生效setBackground 

### ISSUE THREAD

**Issue by Brook688** [LvKang-insist/AndroidSkin#6]
比如setBackgroundColor这种怎么处理？希望能给点思路，谢谢

**Comment by Brook688** [comment]
在Fragment中使用Databinding 为啥可以，在Activity中使用Databinding就无效啊？

**Comment by LvKang-insist** [comment]
你好，有问题可以加微信互相交流 ：WX : LvKang-insist ，QQ 1831712732

**Comment by LvKang-insist** [comment]
> 在Fragment中使用Databinding 可以，在Activity中使用Databinding就无效，😂

你好，有问题可以加微信互相交流 ：WX : LvKang-insist ，QQ 1831712732
